apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
      name: apis
- apiVersion: v1
  kind: Namespace
  metadata:
      name: argo
- apiVersion: v1
  kind: Namespace
  metadata:
      name: loki
- apiVersion: v1
  kind: Namespace
  metadata:
      name: jupyter
- apiVersion: v1
  kind: Namespace
  metadata:
      name: es