apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
      name: apis
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: argo
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: loki
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: jupyter
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: es
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798 
- apiVersion: v1
  kind: Namespace
  metadata:
      name: external-secrets
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: trino
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798
- apiVersion: v1
  kind: Namespace
  metadata:
      name: istio-system
      annotations:
        azure.workload.identity/client-id: 89b7b01d-1859-4a2b-a00f-6ed82a20f390
        azure.workload.identity/tenant-id: 26a1e041-d3a2-4d59-a14a-acaedd98e798 
