apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: argo
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: apis
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: external-secrets
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: trino
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: default
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: loki
- apiVersion: v1
  kind: ServiceAccount
  metadata:
      name: sara
      Namespace: istio-system