apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: argo
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: apis
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: external-secrets
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: trino
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: default
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: loki
  automountServiceAccountToken: false
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: sara
    namespace: istio-system
  automountServiceAccountToken: false
